// <auto-generated />
using Bulky.DataAccess.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Bulky.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContextModelSnapshot)), Migration("20241127140422_AddCategoryTableToDb")]
    internal class AddCategoryTableToDbBase : AddCategoryTableToDbBaseBase
    {
    }
}